-- Production user_subscriptions schema (as deployed on Supabase).
-- API code maps: plan_type <-> tier, search_count_monthly <-> searchesUsed.

-- id uuid PK
-- user_id uuid FK -> users(id)
-- plan_type text (trial | standard | pro)
-- search_count_monthly integer
-- word_downloads_count integer
-- auto_renew boolean
-- expires_at timestamptz nullable
-- user_email text (teacher email, denormalized)
-- user_full_name text (teacher display name)
-- user_phone text (teacher phone)
-- created_at, updated_at timestamptz
