/**
 * languages.js - UI translation dictionary: he, en, de, es
 * Load before i18n-bundle.js
 */
const LANGUAGES = {
  /* ── Hebrew ─────────────────────────────────────────────────────────────── */
  he: {
    meta_title:                  'מתכנן תקופות לימוד | חינוך אנתרופוסופי',
    meta_description:            'מתכנן תקופות לימוד אנתרופוסופי — מסע פדגוגי שלב-אחר-שלב',
    header_tagline:              'חינוך ולדורף · תקופת לימוד ראשית',
    header_title:                'מתכנן תקופות לימוד אנתרופוסופי',
    header_subtitle:             'כיתה ← נושא ← תוצרים, מערכי שיעור ועוד | מאגר קהילתי | ארכיון ידע',
    lang_label:                  'שפה',
    lang_toggle_aria:            'החלף שפה ל-{lang}',
    lang_name_he:                'עברית',
    lang_name_en:                'אנגלית',

    nav_wizard_aria:             'שלבי המסע הפדגוגי',
    nav_community:               'מאגר קהילתי',
    nav_community_aria:          'פתח מאגר קהילתי',
    nav_archive:                 'ארכיון ידע אנתרופוסופי',
    nav_archive_aria:            'פתח ארכיון ידע אנתרופוסופי',
    nav_repo:                    'מאגר',
    nav_repo_aria:               'פתח מאגר חומרים',

    btn_new_research:            'מחקר חדש — איפוס והתחלה מכיתה ונושא',
    step_prefix:                 'שלב',
    step_a_badge:                'שלב א׳',
    step_b_badge:                'שלב ב׳',
    step_c_badge:                'שלב ג׳',
    step_a_grade:                'כיתה',
    step_b_topic:                'נושא',
    step_c_materials:            'תוצרים, מערכי שיעור ועוד',
    step_nav_a:                  'א׳ כיתה',
    step_nav_b:                  'ב׳ נושא',
    step_nav_c:                  'ג׳ תוצרים, מערכי שיעור ועוד',

    step1_title:                 'בחירת כיתה מבוקשת',
    step1_desc:                  'בחרו את שכבת הגיל — לאחר מכן יוצג מיד תמונת הגיל והחומרים השיתופיים לכיתה זו.',
    grade_label:                 'כיתה מבוקשת',
    grade_placeholder:           '— בחרו כיתה —',
    grade_age_prefix:            'גיל',
    btn_grade_submit:            'הצג תמונת גיל וחומרי קהילה',
    grade_insights_default:      'תמונת גיל — מאגר עולמי',
    grade_insights_title:        'תמונת גיל — {grade}',
    grade_insights_sources:      'המערכת מפיקה כעת את תמונת הגיל וההרחבות הפדגוגיות לכיתה שנבחרה...',
    grade_insights_generating:   'מפיק תמונת גיל, רעיונות והרחבות קהילה...',
    grade_research_cancel:       'ביטול ובחירת כיתה מחדש',
    grade_insights_empty:        'לא התקבל תוכן מתמונת הגיל — נסו שוב.',
    community_need_topic:        'הגדירו נושא בשלב ב׳ כדי לראות חומרים מהקהילה.',
    community_empty_topic:       'אין עדיין חומרים מהקהילה לנושא זה.',
    community_materials_title:   'העשרה פדגוגית וחומרים מהקהילה',
    btn_to_step2:                'המשך לשלב ב׳ — הגדרת נושא התקופה',

    step2_title:                 'מה הנושא המבוקש לתקופת הלימוד?',
    step2_desc:                  'המערכת תסרוק את הרשת עבור נושא זה, ותנתח כיצד הוא מתחבר להתפתחות הנפשית-גופנית-רוחנית של הילד בגיל',
    topic_placeholder:           '',
    api_hint_step2:              'חיבור Supabase נדרש — בדקו הגדרות הפרויקט.',
    btn_topic_research:          'חפש ברשת ונתח התאמה לגיל',
    btn_to_workspace:            'המשך לשלב ג׳ — תוצרים, מערכי שיעור ועוד',

    step3_title:                 'חומרי הוראה',
    step3_question:              'אילו חומרים תרצה להוסיף?',
    step3_desc:                  'הוסף חומרים אישיים, קבצי Google Drive וחומרים מהקהילה',
    personal_title_ph:           'כותרת החומר',
    personal_notes_ph:           'הערות אישיות...',
    btn_personal_upload:         'העלה קובץ',
    btn_drive:                   'חבר Google Drive',
    btn_drive_sync:              'סנכרן עם Drive',
    drive_privacy:               'הקבצים נשארים פרטיים שלך',
    btn_unlock_workspace:        'פתח סביבת עבודה',
    ws_active:                   'סביבת עבודה פעילה',
    btn_restart:                 'מחקר חדש',

    crumb_grade:                 'כיתה',
    crumb_topic:                 'נושא',
    crumb_products:              'תוצרים, מערכי שיעור ועוד',
    crumb_community:             'מאגר קהילתי',
    crumb_archive:               'ארכיון ידע',
    breadcrumb_aria:             'נתיב מסע פדגוגי',
    products_tablist_aria:       'תוצרים, מערכי שיעור ועוד',

    tab_theory:                  'רקע תיאורטי',
    tab_theory_suffix:           ' ומקורות',
    tab_inspiration:             'השראה',
    tab_inspiration_suffix:      ' ומקורות',
    tab_archive:                 'ארכיון',
    tab_archive_suffix:          '',
    tab_curriculum:              'תכנון',
    tab_curriculum_suffix:       ' תקופה',

    pinterest_title:             'השראה חזותית ומחברות תקופה',
    pinterest_desc:              'קישורי השראה שנמצאו במחקר החי — Pinterest, ארכיונים וולדורפיים',
    pinterest_board_link:        'לוח השראה',
    share_community:             'שתפו עם הקהילה (ענן)',
    upload_author_ph:            'שמך',
    upload_title_ph:             'כותרת החומר',
    upload_notes_ph:             'תיאור קצר...',
    btn_add_community:           'הוסף לקהילה',

    archive_title:               'ארכיון ידע אנתרופוסופי',
    archive_desc:                'חיפוש במאגרי ידע, הרצאות רודולף שטיינר, מאמרים ומחקרים — מותאם לכיתה ולנושא שנבחרו. לכל מקור: תקציר פדגוגי מעמיק ומורחב בלבד.',
    archive_search_label:        'חיפוש בארכיון',
    archive_search_ph:           'הזן מונח לחיפוש...',
    archive_search_btn:          'חפש',
    archive_api_hint:            'שירות המחקר אינו זמין. ודאו שהאתר נפרס ל-Vercel עם AI_API_KEY מוגדר.',

    curriculum_title:            'תכנון תקופה — 15 ימים',
    expand_all:                  'הרחב את כל הימים',
    curriculum_cards_aria:       'כרטיסי תוכנית לימודים',
    col_day:                     'יום',
    col_topic:                   'נושא',
    col_content:                 'תוכן וסיפור',
    col_art:                     'אמנות ומעשה',
    refresh_cloud:               'רענן מהענן',

    cloud_research_on:           'חיפוש חי (Perplexity) — דרך שרת מאובטח ב-Vercel. מורים אינם מזינים מפתח API.',
    cloud_research_off:          'מחקר ענן כבוי',
    cloud_config_missing:        'הגדירו SUPABASE_URL ו-SUPABASE_ANON_KEY ב-index.html',
    cloud_community_on:          'שיתוף קהילתי בענן פעיל',

    confirm_new_research:        'להתחיל מחקר חדש? השינויים לא יישמרו.',
    personal_default_title:      'חומר אישי',

    grade_insights_loading:      'טוען תובנות...',
    grade_insights_fallback_note:'תובנות אלו מבוססות על ידע כללי של חינוך וולדורף',
    grade_part1_title:           'תמונת הגיל ודגשים פדגוגיים מורחבים',
    grade_part2_title:           'רעיונות פדגוגיים מעשיים לעבודה בכיתה',
    grade_part3_title:           'הרחבות וחומרי קהילה',
    dev_focus:                   'מוקד התפתחותי',
    global_curricula:            'תוכניות לימודים עולמיות',
    sources_label:               'מקורות',
    typical_blocks:              'אפוקות טיפוסיות',

    no_teacher_folders:          'לא נמצאו תיקיות מורה',
    no_community_grade:          'אין חומרים קהילתיים לכיתה זו',
    community_demo:              'חומר הדגמה',
    load_error:                  'שגיאה בטעינה',

    topic_research_scanning:     'סורק את הרשת...',
    topic_research_deep:         'מחקר מעמיק: נושא, תיאוריה, 15 ימי לימוד והשראה ויזואלית...',
    cache_hit_summary:           'נטען מהמאגר — תוכנית מוכנה מיידית (ללא המתנה ל-AI).',
    cache_hit_highlight:         'רקע תיאורטי, השראה ותכנון תקופה — נשלפו מ-Supabase',
    topic_research_cancel:       'ביטול ועריכה מחדש 🛑',
    btn_topic_research_again:    'חפש שוב',
    web_research_title:          'מחקר רשת',
    web_research_age_conn:       'קשר לגיל הכיתה',

    remove_btn:                  'הסר',
    drive_picker_title:          'בחר קובץ מ-Drive',
    drive_file_default:          'קובץ מ-Drive',
    drive_picked:                'נבחר: {name}',
    drive_picked_none:           'לא נבחר קובץ',
    drive_cancelled:             'הבחירה בוטלה',
    drive_merging:               'ממזג חומרים...',
    drive_merge_fallback_title:  'חומר מ-Drive',
    drive_merge_fallback_note:   'תוכן מ-Google Drive',
    drive_merge_insp_note:       'השראה מ-Drive',
    drive_merge_curr_note:       'תוכנית מ-Drive',
    drive_connecting:            'מתחבר ל-Drive...',
    drive_opening_picker:        'פותח בורר קבצים...',
    drive_config_missing:        'הגדרות Drive חסרות',
    drive_syncing:               'מסנכרן...',
    drive_sync_empty:            'לא נמצאו קבצים',
    drive_library_title:         'ספריית Drive',
    drive_library_desc:          'קבצים מ-Google Drive שלך',
    drive_open_folder:           'פתח תיקייה',
    drive_open_file:             'פתח קובץ',
    drive_auto_loaded:           'נטען אוטומטית מ-Drive',

    synthesis_banner:            'הסינתזה מוכנה',
    personal_materials_ws:       'החומרים האישיים שלכם',
    pinterest_board:             'לוח Pinterest',
    pinterest_link:              'קישור ללוח',

    curriculum_day:              'יום {n}',
    curriculum_tap_details:      'הקש לפרטים',
    curriculum_content_label:    'תוכן השיעור',
    curriculum_art_label:        'פעילות אמנותית',
    curriculum_journeys:         'מסלולי למידה',

    no_community_ws:             'אין חומרים קהילתיים לסביבת עבודה זו',
    community_teachers:          'מורים מהקהילה',
    delete_confirm:              'למחוק חומר זה?',
    delete_aria:                 'מחק חומר',
    demo_badge:                  'הדגמה',

    upload_demo_saved:           'נשמר מקומית (כולל קובץ)',
    upload_saved:                'נשמר בקהילה!',
    upload_no_file:              'בחרו קובץ להעלאה',
    upload_uploading:            'מעלה קובץ...',
    upload_saved_local:          'הקובץ נשמר בהצלחה במחשב',
    upload_saved_cloud:          'הקובץ הועלה לענן ונשמר מקומית',
    upload_saved_local_only:     'נשמר מקומית (הענן לא זמין)',
    drive_sync_done:             'נמצאו {count} קבצים, {added} חדשים נוספו',
    upload_updated:              'החומר עודכן',
    file_too_large:              'הקובץ גדול מדי (מקסימום 10MB)',

    archive_alert_empty:         'הזן מונח חיפוש',
    archive_alert_no_api:        'נדרש מפתח API לחיפוש',
    archive_searching:           'מחפש...',
    archive_found:               'נמצאו {n} תוצאות',
    archive_no_results:          'לא נמצאו תוצאות',
    archive_read_full:           'קרא מלא',
    archive_no_link:             'ללא קישור',
    archive_summary_btn:         'סכם',
    archive_summary_title:       'סיכום',
    archive_key_points:          'נקודות מפתח',
    archive_class_angles:        'זוויות לכיתה',
    archive_further_reading:     'קריאה נוספת',
    archive_generating:          'מייצר סיכום...',
    archive_type_book:           'ספר',
    archive_type_lecture:        'הרצאה',
    archive_type_article:        'מאמר',
    archive_type_source:         'מקור',
    archive_untitled:            'ללא כותרת',
    archive_unknown_author:      'מחבר לא ידוע',
    archives_synthesis:          'סינתזה מארכיון',

    teacher_default:             'מורה',

    err_supabase_config:         'שגיאת הגדרות Supabase',
    err_network:                 'שגיאת רשת – בדוק את החיבור',
    err_bad_response:            'תגובה שגויה מהשרת',
    err_function_not_found:      'פונקציה לא נמצאה',
    err_invalid_plan:            'תוכנית לא תקינה',

    phase_opening:               'פתיחה',
    phase_deepening:             'העמקה',
    phase_expanding:             'הרחבה',
    phase_synthesis:             'סינתזה',
    phase_closing:               'סיכום',
    day_n:                       'יום {n}',

    theory_age_topic:            'גיל {age}: {topic}',
    inspiration_visual:          'השראה ויזואלית',
    visual_inspiration_n:        'השראה {n}',
    picker_script_error:         'שגיאה בטעינת בורר Google Drive',

    grade_1: 'כיתה א׳', grade_2: 'כיתה ב׳', grade_3: 'כיתה ג׳', grade_4: 'כיתה ד׳',
    grade_5: 'כיתה ה׳', grade_6: 'כיתה ו׳', grade_7: 'כיתה ז׳', grade_8: 'כיתה ח׳',

    catalog_title:               'מאגר קהילתי',
    catalog_desc:                'בחרו כיתה, העלו חומרים לנושא חדש — או היכנסו לרובריקות שנוצרו על ידי מורים בקהילה.',
    catalog_bc_grades:           'כל הכיתות',
    catalog_choose_grade:        'בחרו כיתה',
    catalog_topics_count:        '{topics} נושאים · {files} קבצים',
    catalog_share_open:          'שתף חומרי לימוד עם הקהילה +',
    catalog_add_material:        'הוסף חומר חדש למאגר +',
    catalog_community_topics:    'רובריקות קהילתיות',
    catalog_no_topics:           'עדיין אין נושאים בכיתה זו — לחצו על «שתף חומרי לימוד עם הקהילה +» כדי להעלות את הראשון, והרובריקה תיווצר אוטומטית.',
    catalog_files_in_topic:      '{count} קבצים',
    catalog_community_files:     'קבצים בקהילה ({count})',
    catalog_no_files:            'אין עדיין קבצים — לחצו על «הוסף חומר חדש למאגר +» כדי להעלות את הראשון.',
    catalog_loading:             'טוען מ-Supabase...',
    catalog_general:             'כללי',
    catalog_upload_title:        'העלאה לקהילה',
    catalog_topic_label:         'שם הנושא',
    catalog_desc_label:          'תיאור קצר של הקובץ',
    catalog_author_label:        'שם המורה (אופציונלי)',
    catalog_share_mode:          'אופן השיתוף',
    catalog_mode_file:           'העלאת קובץ מהמחשב',
    catalog_mode_link:           'שיתוף קישור ל-Google Docs / Google Drive',
    catalog_file_label:          'קובץ',
    catalog_link_label:          'קישור שיתופי',
    catalog_link_aria:           'הדבק כאן את הקישור השיתופי של הקובץ או התיקייה',
    catalog_link_hint:           'הדבק כאן את הקישור השיתופי (URL) של הקובץ או התיקייה.',
    catalog_link_hint_drive:     'אנא ודא שהגדרות השיתוף בגוגל דרייב מוגדרות כ-Anyone with the link (כל אחד עם הקישור יכול לצפות).',
    catalog_submit:              'העלה ל-Supabase',
    catalog_err_topic:           'יש להזין שם נושא',
    catalog_saving_link:         'שומר קישור...',
    catalog_uploading:           'מעלה...',
    catalog_err_link:            'יש להדביק קישור שיתוף',
    catalog_success:             'הועלה בהצלחה לקהילה!',
    community_badge_label:       'קהילה',
    community_no_file:           'אין קובץ מצורף',
    community_link_open:         'פתח קישור',
    community_link_download:     'הורד קובץ',

    theory_bib_title:            '📚 מראי מקום, ספרות ומקורות להעמקה',
    theory_bib_intro:            'מקורות מומלצים להעמקה בנושא «{topic}» — {grade}',
    theory_bib_note:             'מקורות בעברית — אנתרופוסופיה ופדגוגיית ולדורף בלבד. מקורות באנגלית (עד 10). לחצו «הרחבה ואספקטים פרקטיים» להעמקה.',
    theory_bib_note_en:          'Up to 10 leading anthroposophic/Waldorf sources in English. Click «Practical expansion & aspects» to explore.',
    theory_bib_books:            'ספרים ומראי מקום',
    theory_bib_articles:         'מאמרים אנתרופוסופיים ופדגוגיים',
    theory_bib_websites:         'אתרים ומקורות מומלצים',
    theory_bib_empty:            'מקורות יתווספו לאחר מחקר AI מלא.',
    theory_bib_chapter:          'פרק: {chapter}',
    theory_bib_source:           'מקור',
    expansion_practical_btn:     'הרחבה ואספקטים פרקטיים 📝',
    expansion_parent_community:  'מול הורים וקהילה',
    expansion_inspiration_refs:  'חומרי השראה ומקורות מומלצים',
    theory_bib_deep_btn:         'הרחבה ואספקטים פרקטיים 📝',
    inline_expand_close:         'סגור הרחבה',
    theory_bib_summary_title:    'תקציר פדגוגי מעמיק',
    theory_bib_summary_loading:  'מפיק תקציר פדגוגי רחב ומעמיק במיוחד...',
    theory_bib_relevance:        'רלוונטיות לנושא הנלמד',
    theory_bib_key_points:       'נקודות מפתח לשיעור',
    theory_bib_lesson_angles:    'זוויות פדגוגיות לכיתה',
    theory_bib_summary_empty:    'לא נמצא תקציר — נסו שוב.',
    theory_bib_modal_close:      'סגור',

    pedagogy_deep_btn:           'הרחבה ואספקטים פרקטיים 📝',
    pedagogy_modal_title:        'הסבר מלא ומערך פעילות',
    pedagogy_summary_loading:    'מפיק הסבר מפורט, הקשר פדגוגי ושלבי ביצוע...',
    pedagogy_essence:            'מהות הפעילות',
    pedagogy_context:            'הקשר פדגוגי ורלוונטיות לתקופה',
    pedagogy_steps:              'שלבי ביצוע פרקטיים בכיתה',
    pedagogy_materials:          'חומרים ומשאבים נדרשים',
    pedagogy_summary_empty:      'לא נמצא הסבר — נסו שוב.',
    pedagogy_inspiration_hint:   'לחצו «הרחבה ואספקטים פרקטיים» ליד כל רעיון ליישום מעשי בכיתה וחומרי השראה.',
    pedagogy_narrative_title:    'מטאפורות ונרטיב לתקופה',

    synthesis_banner_title:      'סינתזה מאוחדת:',
    synthesis_web:               'מחקר רשת',
    synthesis_grade:             'תמונת גיל',
    synthesis_community:         'חומרי קהילה',
    synthesis_personal:          'חומרים אישיים',
    synthesis_drive:             ' (כולל Drive)',

    drive_merge_insp_note:       'שולב אוטומטית לשכבת ההשראה (טאב 2) לאחר סריקת Drive.',
    drive_merge_curr_note:       'שולב אוטומטית לתכנון התקופה (טאב 3).',

    curriculum_day_short:        'יום {day}',
    curriculum_tap_full:         'הקשו לפרטים מלאים',
    curriculum_journey_prefix:   'מסעות בחינוך:',
    curriculum_journey_map:      'נקודה על המפה — יום {day}',

    community_hint_prefix:       'הועלו',
    community_hint_link:         'חומרי לימוד',
    community_hint_suffix:       'אחרים מהקהילה ל-{grade}!',

    btn_export_pedagogy_doc:     'הפקת מסמך סיכום פדגוגי למורה 📄',
    export_doc_main_title:       'מסמך סיכום פדגוגי - ארכיון ולדורף',
    export_doc_filename:         'סיכום פדגוגי - כיתה {grade} - {topic}.docx',
    export_doc_grade_line:       'כיתה: {grade} (גיל {age})',
    export_doc_topic_line:       'נושא התקופה: {topic}',
    export_doc_section_grade:    'שלב א׳ — תמונת גיל והעשרה',
    export_doc_section_web:      'שלב ב׳ — מחקר נושא ברשת',
    export_doc_section_theory:   'שלב ג׳ — רקע תיאורטי',
    export_doc_section_inspiration:'שלב ג׳ — השראה',
    export_doc_section_curriculum: 'שלב ג׳ — תכנון תקופה',
    export_doc_section_other:    'הרחבות נוספות',
    export_doc_expansions_title: 'אספקטים פרקטיים שנבחרו להרחבה',
    export_doc_web_connections:  'חיבור לגיל',
    export_doc_no_topic:         'ללא נושא',
    export_doc_need_grade:       'יש לבחור כיתה לפני הפקת המסמך',
    export_doc_error:            'שגיאה בהפקת המסמך',
    export_doc_generating:       'מפיק מסמך...',

    auth_subtitle:               'הצטרפו למסע הפדגוגי — גישה למחקר חי, מאגר קהילתי וארכיון ידע',
    auth_tab_login:              'כניסה',
    auth_tab_signup:             'הרשמה',
    auth_email_label:            'דוא״ל',
    auth_password_label:         'סיסמה',
    auth_name_label:             'שם מלא',
    auth_login_btn:              'היכנסו למערכת',
    auth_signup_btn:             'התחילו ניסיון חינם',
    auth_err_required:             'נא למלא דוא״ל וסיסמה',
    auth_err_sign_in_first:      'יש להתחבר לפני שדרוג',
    auth_signout:                'יציאה',
    auth_upgrade:                'שדרוג',
    auth_google_btn:             'התחברות באמצעות גוגל',
    auth_or_email:               'או עם דוא״ל',
    auth_loading:                'מתחברים...',
    auth_loading_session:        'בודקים חיבור...',
    auth_err_supabase:           'שגיאת התחברות — נסו שוב',
    auth_confirm_email:          'נשלח אימייל לאימות — אשרו את החשבון ואז התחברו',

    tier_trial_name:             'ניסיון 7 ימים',
    tier_educator_name:          'מסלול מחנך/ת',
    tier_expert_name:            'מסלול מומחה/ית',
    tier_searches_per_day:       'עד {count} חיפושים ביום',
    tier_expert_searches:        'חיפושים ללא הגבלה',
    tier_trial_feature:          'גישה מלאה ל-7 ימים — מושלם להכרת המערכת',
    tier_educator_feature_1:     'מסלול יומיומי למורים בכיתה',
    tier_educator_feature_2:     'מאגר קהילתי וארכיון ידע',
    tier_expert_feature_1:       'ללא הגבלת חיפושים יומית',
    tier_expert_feature_2:       'למנהלי תוכניות ומפתחי תקופות',

    pricing_title:               'בחרו את המסלול שלכם',
    pricing_subtitle:            'תמחור שקוף למורים ולצוותים פדגוגיים',
    pricing_free:                'חינם',
    pricing_per_month:           '/חודש',
    pricing_per_year:            '/שנה',
    pricing_or_yearly:           'או {amount} ₪ לשנה',
    pricing_or_monthly:          'או {amount} ₪ לחודש',
    pricing_most_popular:        'הכי פופולרי',
    pricing_current_plan:        'המסלול הנוכחי',
    pricing_start_trial:         'התחילו ניסיון',
    pricing_upgrade_btn:         'שדרגו עכשיו',
    pricing_billing_monthly:     'חודשי',
    pricing_billing_yearly:      'שנתי',
    pricing_close:               'סגור',

    search_usage_label:          'חיפושים היום',
    search_usage_today_unlimited:'חיפושים היום',

    rate_limit_title:            'הגעתם למכסת החיפושים היומית',
    rate_limit_body:             'ניצלתם {used} מתוך {limit} חיפושים היום. שדרגו מסלול כדי להמשיך במחקר פדגוגי.',
    rate_limit_exceeded:         'חרגתם ממכסת החיפושים היומית — שדרגו את המסלול',
    rate_limit_upgrade:          'צפו במסלולים ושדרגו',
    rate_limit_dismiss:          'הבנתי',
  },

  /* ── English ─────────────────────────────────────────────────────────────── */
  en: {
    meta_title:                  'Main Lesson Planner | Anthroposophic Education',
    meta_description:            'Anthroposophic main lesson planner — step-by-step pedagogical journey',
    header_tagline:              'Waldorf Education · Main Lesson Block',
    header_title:                'Anthroposophic Main Lesson Planner',
    header_subtitle:             'Grade → Topic → Outputs & lesson plans | Community database | Knowledge archive',
    lang_label:                  'Language',
    lang_toggle_aria:            'Switch language to {lang}',
    lang_name_he:                'Hebrew',
    lang_name_en:                'English',

    nav_wizard_aria:             'Pedagogical journey steps',
    nav_community:               'Community Database',
    nav_community_aria:          'Open community database',
    nav_archive:                 'Anthroposophical Archive',
    nav_archive_aria:            'Open anthroposophical knowledge archive',
    nav_repo:                    'Repository',
    nav_repo_aria:               'Open materials repository',

    btn_new_research:            'New research — reset and start from grade & topic',
    step_prefix:                 'Step',
    step_a_badge:                'Step A',
    step_b_badge:                'Step B',
    step_c_badge:                'Step C',
    step_a_grade:                'Grade',
    step_b_topic:                'Topic',
    step_c_materials:            'Outputs & Lesson Plans',
    step_nav_a:                  'A: Grade',
    step_nav_b:                  'B: Topic',
    step_nav_c:                  'C: Outputs & Lesson Plans',

    step1_title:                 'Select Target Grade',
    step1_desc:                  'Choose the age group — you will then see the developmental picture and shared community materials for that grade.',
    grade_label:                 'Target grade',
    grade_placeholder:           '— Select a grade —',
    grade_age_prefix:            'Age',
    btn_grade_submit:            'Show age picture & community materials',
    grade_insights_default:      'Age picture — global repository',
    grade_insights_title:        'Age picture — {grade}',
    grade_insights_sources:      'The system is now producing the age picture and pedagogical expansions for the selected grade...',
    grade_insights_generating:   'Producing age picture, ideas and community expansions...',
    grade_research_cancel:       'Cancel and choose grade again',
    grade_insights_empty:        'No age-picture content received — please try again.',
    community_need_topic:        'Define a topic in Step B to see community materials.',
    community_empty_topic:       'No community materials for this topic yet.',
    community_materials_title:   'Pedagogical enrichment & community materials',
    btn_to_step2:                'Continue to Step B — define the block topic',

    step2_title:                 'What is the main lesson topic?',
    step2_desc:                  'The system will scan the web for this topic and analyze how it connects to the child\'s soul-body-spirit development at this age.',
    topic_placeholder:           '',
    api_hint_step2:              'Supabase connection required — check project settings.',
    btn_topic_research:          'Search the web & analyze age fit',
    btn_to_workspace:            'Continue to Step C — outputs & lesson plans',

    step3_title:                 'Teaching Materials',
    step3_question:              'What materials would you like to add?',
    step3_desc:                  'Add personal materials, Google Drive files and community resources',
    personal_title_ph:           'Material title',
    personal_notes_ph:           'Personal notes…',
    btn_personal_upload:         'Upload File',
    btn_drive:                   'Connect Google Drive',
    btn_drive_sync:              'Sync with Drive',
    drive_privacy:               'Files remain private to you',
    btn_unlock_workspace:        'Unlock Workspace',
    ws_active:                   'Workspace Active',
    btn_restart:                 'New research',

    crumb_grade:                 'Grade',
    crumb_topic:                 'Topic',
    crumb_products:              'Outputs & Lesson Plans',
    crumb_community:             'Community Database',
    crumb_archive:               'Knowledge Archive',
    breadcrumb_aria:             'Pedagogical journey path',
    products_tablist_aria:       'Outputs, lesson plans and more',

    tab_theory:                  'Theoretical Background',
    tab_theory_suffix:           ' & Sources',
    tab_inspiration:             'Inspiration',
    tab_inspiration_suffix:      ' & Sources',
    tab_archive:                 'Archive',
    tab_archive_suffix:          '',
    tab_curriculum:              'Block',
    tab_curriculum_suffix:       ' Planning',

    pinterest_title:             'Visual inspiration & block notebooks',
    pinterest_desc:              'Inspiration links from live research — Pinterest, Waldorf archives',
    pinterest_board_link:        'Inspiration board',
    share_community:             'Share with the community (cloud)',
    upload_author_ph:            'Your name',
    upload_title_ph:             'Material title',
    upload_notes_ph:             'Brief description…',
    btn_add_community:           'Add to Community',

    archive_title:               'Anthroposophical Knowledge Archive',
    archive_desc:                'Search knowledge bases, Rudolf Steiner lectures, articles and research — tailored to the selected grade and topic. Each source: deep expanded pedagogical summary only.',
    archive_search_label:        'Search Archive',
    archive_search_ph:           'Enter search term…',
    archive_search_btn:          'Search archive',
    archive_api_hint:            'Research service unavailable. Ensure the site is deployed on Vercel with AI_API_KEY configured.',

    curriculum_title:            'Block planning — 15 days',
    expand_all:                  'Expand all days',
    curriculum_cards_aria:       'Curriculum cards',
    col_day:                     'Day',
    col_topic:                   'Topic',
    col_content:                 'Content & story',
    col_art:                     'Art & craft',
    refresh_cloud:               'Refresh from cloud',

    cloud_research_on:           'Live search (Perplexity) — via secure Vercel server. Teachers do not enter an API key.',
    cloud_research_off:          'Cloud research off',
    cloud_config_missing:        'Set SUPABASE_URL and SUPABASE_ANON_KEY in index.html',
    cloud_community_on:          'Cloud community sharing active',

    confirm_new_research:        'Start new research? Unsaved changes will be lost.',
    personal_default_title:      'Personal Material',

    grade_insights_loading:      'Loading insights…',
    grade_insights_fallback_note:'These insights are based on general Waldorf education knowledge',
    grade_part1_title:           'Age picture & expanded pedagogical emphases',
    grade_part2_title:           'Practical pedagogical ideas for the classroom',
    grade_part3_title:           'Expansions & community materials',
    dev_focus:                   'Developmental Focus',
    global_curricula:            'Global Curricula',
    sources_label:               'Sources',
    typical_blocks:              'Typical Main Lesson Blocks',

    no_teacher_folders:          'No teacher folders found',
    no_community_grade:          'No community materials for this grade',
    community_demo:              'Demo material',
    load_error:                  'Loading error',

    topic_research_scanning:     'Scanning the web...',
    topic_research_deep:         'Deep research: topic, theory, 15 lesson days & visual inspiration...',
    cache_hit_summary:           'Loaded from cache — instant lesson plan (no AI wait).',
    cache_hit_highlight:         'Theory, inspiration & block planning — fetched from Supabase',
    topic_research_cancel:       'Cancel & edit again 🛑',
    btn_topic_research_again:    'Search again',
    web_research_title:          'Web Research',
    web_research_age_conn:       'Connection to class age',

    remove_btn:                  'Remove',
    drive_picker_title:          'Select file from Drive',
    drive_file_default:          'File from Drive',
    drive_picked:                'Selected: {name}',
    drive_picked_none:           'No file selected',
    drive_cancelled:             'Selection cancelled',
    drive_merging:               'Merging materials…',
    drive_merge_fallback_title:  'Drive Material',
    drive_merge_fallback_note:   'Content from Google Drive',
    drive_merge_insp_note:       'Automatically merged into the inspiration layer (tab 2) after Drive scan.',
    drive_merge_curr_note:       'Automatically merged into block planning (tab 3).',
    drive_connecting:            'Connecting to Drive…',
    drive_opening_picker:        'Opening file picker…',
    drive_config_missing:        'Drive configuration missing',
    drive_syncing:               'Syncing…',
    drive_sync_done:             'Found {count} files, {added} new items added',
    drive_sync_empty:            'No files found',
    drive_library_title:         'Drive Library',
    drive_library_desc:          'Files from your Google Drive',
    drive_open_folder:           'Open Folder',
    drive_open_file:             'Open File',
    drive_auto_loaded:           'Auto-loaded from Drive',

    synthesis_banner:            'Synthesis ready',
    personal_materials_ws:       'Your personal materials',
    pinterest_board:             'Pinterest Board',
    pinterest_link:              'Board link',

    curriculum_day:              'Day {n}',
    curriculum_tap_details:      'Tap for details',
    curriculum_content_label:    'Lesson content',
    curriculum_art_label:        'Art & craft',
    curriculum_journeys:         'Learning journeys',
    curriculum_day_short:        'Day {day}',
    curriculum_tap_full:         'Tap for full details',
    curriculum_journey_prefix:   'Educational journeys:',
    curriculum_journey_map:      'Point on the map — day {day}',

    no_community_ws:             'No community materials for this workspace',
    community_teachers:          'Community Teachers',
    delete_confirm:              'Delete this material?',
    delete_aria:                 'Delete material',
    demo_badge:                  'Demo',

    upload_demo_saved:           'Saved locally (including file)',
    upload_saved:                'Saved to community!',
    upload_no_file:              'Please select a file to upload',
    upload_uploading:            'Uploading file...',
    upload_saved_local:          'File saved locally on your device',
    upload_saved_cloud:          'File uploaded to cloud and saved locally',
    upload_saved_local_only:     'Saved locally (cloud unavailable)',
    upload_updated:              'Material updated',
    file_too_large:              'File is too large (max 10 MB)',

    archive_alert_empty:         'Please enter a search term',
    archive_alert_no_api:        'An API key is required for search',
    archive_searching:           'Searching…',
    archive_found:               '{n} results found',
    archive_no_results:          'No results found',
    archive_read_full:           'Read full',
    archive_no_link:             'No link',
    archive_summary_btn:         'Summarize',
    archive_summary_title:       'Summary',
    archive_key_points:          'Key Points',
    archive_class_angles:        'Classroom Angles',
    archive_further_reading:     'Further Reading',
    archive_generating:          'Generating summary…',
    archive_type_book:           'Book',
    archive_type_lecture:        'Lecture',
    archive_type_article:        'Article',
    archive_type_source:         'Source',
    archive_untitled:            'Untitled',
    archive_unknown_author:      'Unknown author',
    archives_synthesis:          'Archive Synthesis',

    teacher_default:             'Teacher',

    err_supabase_config:         'Supabase configuration error',
    err_network:                 'Network error – check your connection',
    err_bad_response:            'Bad response from server',
    err_function_not_found:      'Function not found',
    err_invalid_plan:            'Invalid plan',

    phase_opening:               'Opening',
    phase_deepening:             'Deepening',
    phase_expanding:             'Expanding',
    phase_synthesis:             'Synthesis',
    phase_closing:               'Closing',
    day_n:                       'Day {n}',

    theory_age_topic:            'Age {age}: {topic}',
    inspiration_visual:          'Visual Inspiration',
    visual_inspiration_n:        'Inspiration {n}',
    picker_script_error:         'Error loading Google Drive picker',

    grade_1: 'Grade 1', grade_2: 'Grade 2', grade_3: 'Grade 3', grade_4: 'Grade 4',
    grade_5: 'Grade 5', grade_6: 'Grade 6', grade_7: 'Grade 7', grade_8: 'Grade 8',

    catalog_title:               'Community Database',
    catalog_desc:                'Choose a grade, upload materials for a new topic — or browse folders created by teachers in the community.',
    catalog_bc_grades:           'All grades',
    catalog_choose_grade:        'Choose a grade',
    catalog_topics_count:        '{topics} topics · {files} files',
    catalog_share_open:          'Share learning materials with the community +',
    catalog_add_material:        'Add new material to the database +',
    catalog_community_topics:    'Community folders',
    catalog_no_topics:           'No topics in this grade yet — click «Share learning materials with the community +» to upload the first one; the folder will be created automatically.',
    catalog_files_in_topic:      '{count} files',
    catalog_community_files:     'Community files ({count})',
    catalog_no_files:            'No files yet — click «Add new material to the database +» to upload the first one.',
    catalog_loading:             'Loading from Supabase...',
    catalog_general:             'General',
    catalog_upload_title:        'Upload to community',
    catalog_topic_label:         'Topic name',
    catalog_desc_label:          'Short file description',
    catalog_author_label:        'Teacher name (optional)',
    catalog_share_mode:          'Sharing method',
    catalog_mode_file:           'Upload file from computer',
    catalog_mode_link:           'Share Google Docs / Google Drive link',
    catalog_file_label:          'File',
    catalog_link_label:          'Share link',
    catalog_link_aria:           'Paste the share link for the file or folder here',
    catalog_link_hint:           'Paste the share URL for the file or folder here.',
    catalog_link_hint_drive:     'Ensure Google Drive sharing is set to Anyone with the link can view.',
    catalog_submit:              'Upload to Supabase',
    catalog_err_topic:           'Please enter a topic name',
    catalog_saving_link:         'Saving link...',
    catalog_uploading:           'Uploading...',
    catalog_err_link:            'Please paste a share link',
    catalog_success:             'Uploaded successfully to the community!',
    community_badge_label:       'Community',
    community_no_file:           'No file attached',
    community_link_open:         'Open link',
    community_link_download:     'Download file',

    theory_bib_title:            '📚 Bibliography, literature & sources for deepening',
    theory_bib_intro:            'Recommended sources for «{topic}» — {grade}',
    theory_bib_note:             'Hebrew sources — anthroposophy & Waldorf only. English sources (up to 10). Click «Practical expansion & aspects» to explore.',
    theory_bib_note_en:          'Up to 10 leading anthroposophic/Waldorf sources in English. Click «Practical expansion & aspects» to explore.',
    theory_bib_books:            'Books & references',
    theory_bib_articles:         'Anthroposophic & pedagogical articles',
    theory_bib_websites:         'Websites & recommended sources',
    theory_bib_empty:            'Sources will appear after a full AI research run.',
    theory_bib_chapter:          'Chapter: {chapter}',
    theory_bib_source:           'Source',
    expansion_practical_btn:     'Practical expansion & aspects 📝',
    expansion_parent_community:  'With parents & community',
    expansion_inspiration_refs:  'Inspiration & recommended sources',
    theory_bib_deep_btn:         'Practical expansion & aspects 📝',
    inline_expand_close:         'Close expansion',
    theory_bib_summary_title:    'Pedagogical deep summary',
    theory_bib_summary_loading:  'Generating an exceptionally broad, deep pedagogical summary...',
    theory_bib_relevance:        'Relevance to the current topic',
    theory_bib_key_points:       'Key lesson points',
    theory_bib_lesson_angles:    'Pedagogical angles for class',
    theory_bib_summary_empty:    'No summary available — try again.',
    theory_bib_modal_close:      'Close',

    pedagogy_deep_btn:           'Practical expansion & aspects 📝',
    pedagogy_modal_title:        'Full guide & activity plan',
    pedagogy_summary_loading:    'Generating detailed guide, context & steps...',
    pedagogy_essence:            'Activity essence',
    pedagogy_context:            'Pedagogical context & block relevance',
    pedagogy_steps:              'Practical classroom steps',
    pedagogy_materials:          'Materials & resources',
    pedagogy_summary_empty:      'No expansion available — try again.',
    pedagogy_inspiration_hint:   'Click «Practical expansion & aspects» next to each idea for classroom implementation and inspiration.',
    pedagogy_narrative_title:    'Metaphors & narrative for the block',

    synthesis_banner_title:      'Unified synthesis:',
    synthesis_web:               'Web research',
    synthesis_grade:             'Age picture',
    synthesis_community:         'community materials',
    synthesis_personal:          'personal materials',
    synthesis_drive:             ' (incl. Drive)',

    community_hint_prefix:       'Other',
    community_hint_link:         'learning materials',
    community_hint_suffix:       'were shared for {grade} in the community — click to browse.',

    btn_export_pedagogy_doc:     'Export pedagogical summary document 📄',
    export_doc_main_title:       'Pedagogical Summary — Waldorf Archive',
    export_doc_filename:         'Pedagogical summary - {grade} - {topic}.docx',
    export_doc_grade_line:       'Grade: {grade} (age {age})',
    export_doc_topic_line:       'Block topic: {topic}',
    export_doc_section_grade:    'Step A — Age picture & enrichment',
    export_doc_section_web:      'Step B — Topic web research',
    export_doc_section_theory:   'Step C — Theoretical background',
    export_doc_section_inspiration:'Step C — Inspiration',
    export_doc_section_curriculum: 'Step C — Block planning',
    export_doc_section_other:    'Additional expansions',
    export_doc_expansions_title: 'Practical aspects opened for expansion',
    export_doc_web_connections:  'Age connections',
    export_doc_no_topic:         'no topic',
    export_doc_need_grade:       'Select a grade before exporting the document',
    export_doc_error:            'Document export failed',
    export_doc_generating:       'Generating document...',

    auth_subtitle:               'Join the pedagogical journey — live research, community database & knowledge archive',
    auth_tab_login:              'Sign in',
    auth_tab_signup:             'Sign up',
    auth_email_label:            'Email',
    auth_password_label:         'Password',
    auth_name_label:             'Full name',
    auth_login_btn:              'Enter the platform',
    auth_signup_btn:             'Start free trial',
    auth_err_required:           'Please enter email and password',
    auth_err_sign_in_first:      'Please sign in before upgrading',
    auth_signout:                'Sign out',
    auth_upgrade:                'Upgrade',
    auth_google_btn:             'Continue with Google',
    auth_or_email:               'or with email',
    auth_loading:                'Signing in...',
    auth_loading_session:        'Checking session...',
    auth_err_supabase:           'Sign-in failed — please try again',
    auth_confirm_email:          'Confirmation email sent — verify your account, then sign in',

    tier_trial_name:             '7-Day Free Trial',
    tier_educator_name:          'Educator Tier',
    tier_expert_name:            'Expert Tier',
    tier_searches_per_day:       'Up to {count} searches per day',
    tier_expert_searches:        'Unlimited searches',
    tier_trial_feature:          'Full access for 7 days — perfect to explore the platform',
    tier_educator_feature_1:     'Daily workflow for classroom teachers',
    tier_educator_feature_2:     'Community database & knowledge archive',
    tier_expert_feature_1:       'No daily search cap',
    tier_expert_feature_2:       'For curriculum leads & block developers',

    pricing_title:               'Choose your plan',
    pricing_subtitle:            'Transparent pricing for teachers and pedagogical teams',
    pricing_free:                'Free',
    pricing_per_month:           '/month',
    pricing_per_year:            '/year',
    pricing_or_yearly:           'or {amount} NIS/year',
    pricing_or_monthly:          'or {amount} NIS/month',
    pricing_most_popular:        'Most popular',
    pricing_current_plan:        'Current plan',
    pricing_start_trial:         'Start trial',
    pricing_upgrade_btn:         'Upgrade now',
    pricing_billing_monthly:     'Monthly',
    pricing_billing_yearly:      'Yearly',
    pricing_close:               'Close',

    search_usage_label:          'Searches today',
    search_usage_today_unlimited:'searches today',

    rate_limit_title:            'Daily search limit reached',
    rate_limit_body:             'You have used {used} of {limit} searches today. Upgrade your plan to continue pedagogical research.',
    rate_limit_exceeded:         'Daily search limit exceeded — please upgrade your plan',
    rate_limit_upgrade:          'View plans & upgrade',
    rate_limit_dismiss:          'Got it',
  },

  /* ── German ──────────────────────────────────────────────────────────────── */
  de: {
    meta_title:                  'Waldorf-Stundenplaner',
    meta_description:            'KI-gestütztes Werkzeug zur Planung von Waldorf-Hauptunterricht für die Klassen 1–8',
    header_tagline:              'Waldorfpädagogik',
    header_title:                'Stundenplaner',
    header_subtitle:             'KI-gestützte Hauptunterrichtsplanung',
    lang_label:                  'Sprache',

    nav_wizard_aria:             'Assistent zur Stundenplanung',
    nav_repo:                    'Materialien',
    nav_repo_aria:               'Materialarchiv öffnen',
    nav_archive:                 'Archiv',
    nav_archive_aria:            'Artikelarchiv öffnen',

    btn_new_research:            'Neue Recherche',
    step_prefix:                 'Schritt',
    step_a_badge:                'A',
    step_b_badge:                'B',
    step_c_badge:                'C',
    step_a_grade:                'Klasse',
    step_b_topic:                'Thema',
    step_c_materials:            'Materialien',

    step1_title:                 'Klasse wählen',
    step1_desc:                  'Wähle deine Klasse, um den empfohlenen Lehrplan zu entdecken',
    grade_label:                 'Klasse',
    grade_placeholder:           'Klasse wählen…',
    grade_age_prefix:            'Alter',
    btn_grade_submit:            'Weiter zum Thema',
    grade_insights_default:      'Wähle eine Klasse, um Einblicke zu erhalten',
    grade_insights_title:        'Einblicke für Klasse {grade}',
    grade_insights_sources:      'Das System erstellt derzeit das Entwicklungsbild und pädagogische Erweiterungen für die gewählte Klasse...',
    grade_insights_generating:   'Entwicklungsbild, Ideen und Gemeinschaftserweiterungen werden erstellt...',
    grade_research_cancel:       'Abbrechen und Klasse neu wählen',
    grade_insights_empty:        'Kein Entwicklungsbild erhalten — bitte erneut versuchen.',
    community_need_topic:        'Definieren Sie in Schritt B ein Thema, um Gemeinschaftsmaterialien zu sehen.',
    community_empty_topic:       'Noch keine Gemeinschaftsmaterialien zu diesem Thema.',
    community_materials_title:   'Gemeinschaftsmaterialien',
    btn_to_step2:                'Weiter zum Thema',

    step2_title:                 'Thema wählen',
    step2_desc:                  'Gib ein Thema für eine vertiefte Untersuchung ein',
    topic_placeholder:           '',
    api_hint_step2:              'Erfordert einen aktiven API-Schlüssel',
    btn_topic_research:          'Thema erforschen',
    btn_to_step3:                'Weiter zu Materialien',

    step3_title:                 'Unterrichtsmaterialien',
    step3_question:              'Welche Materialien möchtest du hinzufügen?',
    step3_desc:                  'Füge persönliche Materialien, Google-Drive-Dateien und Gemeinschaftsressourcen hinzu',
    personal_title_ph:           'Materialtitel',
    personal_notes_ph:           'Persönliche Notizen…',
    btn_personal_upload:         'Datei hochladen',
    btn_drive:                   'Google Drive verbinden',
    btn_drive_sync:              'Mit Drive synchronisieren',
    drive_privacy:               'Dateien bleiben privat',
    btn_unlock_workspace:        'Arbeitsbereich öffnen',
    ws_active:                   'Arbeitsbereich aktiv',
    btn_restart:                 'Neu beginnen',

    tab_theory:                  'Theorie',
    tab_theory_suffix:           ' + Quellen',
    tab_inspiration:             'Inspiration',
    tab_inspiration_suffix:      '',
    tab_archive:                 'Archiv',
    tab_archive_suffix:          '',
    tab_curriculum:              'Lehrplan',
    tab_curriculum_suffix:       '',

    pinterest_title:             'Pinterest-Boards',
    pinterest_desc:              'Visuelle Inspiration für deinen Unterricht entdecken',
    share_community:             'Mit Gemeinschaft teilen',
    upload_author_ph:            'Dein Name',
    upload_title_ph:             'Materialtitel',
    upload_notes_ph:             'Kurze Beschreibung…',
    btn_add_community:           'Zur Gemeinschaft hinzufügen',

    archive_title:               'Artikelarchiv',
    archive_desc:                'Artikel und Forschung zur Waldorfpädagogik durchsuchen',
    archive_search_label:        'Archiv durchsuchen',
    archive_search_ph:           'Suchbegriff eingeben…',
    archive_search_btn:          'Suchen',
    archive_api_hint:            'Erfordert API-Schlüssel',

    curriculum_title:            'Unterrichtslehrplan',
    expand_all:                  'Alle ausklappen',
    curriculum_cards_aria:       'Lehrplankarten',
    col_day:                     'Tag',
    col_topic:                   'Thema',
    col_content:                 'Inhalt',
    col_art:                     'Kunst',
    refresh_cloud:               'Aktualisieren',

    cloud_research_on:           'Cloud-Recherche aktiv',
    cloud_research_off:          'Cloud-Recherche inaktiv',
    cloud_community_on:          'Cloud-Gemeinschaft aktiv',

    confirm_new_research:        'Neue Recherche starten? Nicht gespeicherte Änderungen gehen verloren.',
    personal_default_title:      'Persönliches Material',

    grade_insights_loading:      'Einblicke werden geladen…',
    grade_insights_fallback_note:'Diese Einblicke basieren auf allgemeinem Waldorf-Pädagogikwissen',
    grade_part1_title:           'Entwicklungsbild & pädagogische Schwerpunkte',
    grade_part2_title:           'Praktische pädagogische Ideen für den Unterricht',
    grade_part3_title:           'Erweiterungen & Gemeinschaftsmaterialien',
    dev_focus:                   'Entwicklungsschwerpunkt',
    global_curricula:            'Weltweite Lehrpläne',
    sources_label:               'Quellen',
    typical_blocks:              'Typische Hauptunterrichtsepochen',

    no_teacher_folders:          'Keine Lehrerordner gefunden',
    no_community_grade:          'Keine Gemeinschaftsmaterialien für diese Klasse',
    community_demo:              'Demonstrationsmaterial',
    load_error:                  'Ladefehler',

    topic_research_scanning:     'Quellen werden durchsucht…',
    topic_research_deep:         'Tiefenrecherche läuft…',
    btn_topic_research_again:    'Erneut recherchieren',
    web_research_title:          'Web-Recherche',
    web_research_age_conn:       'Bezug zum Klassenalter',

    remove_btn:                  'Entfernen',
    drive_picker_title:          'Datei aus Drive auswählen',
    drive_file_default:          'Datei aus Drive',
    drive_picked:                'Ausgewählt: {name}',
    drive_picked_none:           'Keine Datei ausgewählt',
    drive_cancelled:             'Auswahl abgebrochen',
    drive_merging:               'Materialien werden zusammengeführt…',
    drive_merge_fallback_title:  'Drive-Material',
    drive_merge_fallback_note:   'Inhalt aus Google Drive',
    drive_merge_insp_note:       'Inspiration aus Drive',
    drive_merge_curr_note:       'Lehrplan aus Drive',
    drive_connecting:            'Verbindung zu Drive wird hergestellt…',
    drive_opening_picker:        'Dateiauswahl wird geöffnet…',
    drive_config_missing:        'Drive-Konfiguration fehlt',
    drive_syncing:               'Synchronisierung läuft…',
    drive_sync_done:             '{count} Dateien gefunden, {added} neue hinzugefügt',
    drive_sync_empty:            'Keine Dateien gefunden',
    drive_library_title:         'Drive-Bibliothek',
    drive_library_desc:          'Dateien aus deinem Google Drive',
    drive_open_folder:           'Ordner öffnen',
    drive_open_file:             'Datei öffnen',
    drive_auto_loaded:           'Automatisch aus Drive geladen',

    synthesis_banner:            'Synthese bereit',
    personal_materials_ws:       'Persönliche Materialien',
    pinterest_board:             'Pinterest-Board',
    pinterest_link:              'Board-Link',

    curriculum_day:              'Tag {n}',
    curriculum_tap_details:      'Tippen für Details',
    curriculum_content_label:    'Stundeninhalt',
    curriculum_art_label:        'Künstlerische Aktivität',
    curriculum_journeys:         'Lernreisen',

    no_community_ws:             'Keine Gemeinschaftsmaterialien für diesen Arbeitsbereich',
    community_teachers:          'Lehrer der Gemeinschaft',
    delete_confirm:              'Dieses Material löschen?',
    delete_aria:                 'Material löschen',
    demo_badge:                  'Demo',

    upload_demo_saved:           'Lokal gespeichert (inkl. Datei)',
    upload_saved:                'In der Community gespeichert!',
    upload_no_file:              'Bitte wählen Sie eine Datei zum Hochladen',
    upload_uploading:            'Datei wird hochgeladen...',
    upload_saved_local:          'Datei lokal auf Ihrem Gerät gespeichert',
    upload_saved_cloud:          'Datei in die Cloud hochgeladen und lokal gespeichert',
    upload_saved_local_only:     'Lokal gespeichert (Cloud nicht verfügbar)',
    upload_updated:              'Material aktualisiert',
    file_too_large:              'Datei ist zu groß (max. 10 MB)',

    archive_alert_empty:         'Bitte einen Suchbegriff eingeben',
    archive_alert_no_api:        'Für die Suche wird ein API-Schlüssel benötigt',
    archive_searching:           'Suche läuft…',
    archive_found:               '{n} Ergebnisse gefunden',
    archive_no_results:          'Keine Ergebnisse gefunden',
    archive_read_full:           'Volltext lesen',
    archive_no_link:             'Kein Link',
    archive_summary_btn:         'Zusammenfassen',
    archive_summary_title:       'Zusammenfassung',
    archive_key_points:          'Kernpunkte',
    archive_class_angles:        'Perspektiven für die Klasse',
    archive_further_reading:     'Weiterführende Literatur',
    archive_generating:          'Zusammenfassung wird erstellt…',
    archive_type_book:           'Buch',
    archive_type_lecture:        'Vortrag',
    archive_type_article:        'Artikel',
    archive_type_source:         'Quelle',
    archive_untitled:            'Ohne Titel',
    archive_unknown_author:      'Unbekannter Autor',
    archives_synthesis:          'Archiv-Synthese',

    teacher_default:             'Lehrer/in',

    err_supabase_config:         'Supabase-Konfigurationsfehler',
    err_network:                 'Netzwerkfehler – Verbindung prüfen',
    err_bad_response:            'Ungültige Serverantwort',
    err_function_not_found:      'Funktion nicht gefunden',
    err_invalid_plan:            'Ungültiger Plan',

    phase_opening:               'Einstieg',
    phase_deepening:             'Vertiefung',
    phase_expanding:             'Erweiterung',
    phase_synthesis:             'Synthese',
    phase_closing:               'Abschluss',
    day_n:                       'Tag {n}',

    theory_age_topic:            'Alter {age}: {topic}',
    inspiration_visual:          'Visuelle Inspiration',
    visual_inspiration_n:        'Inspiration {n}',
    picker_script_error:         'Fehler beim Laden der Google-Drive-Auswahl',

    btn_export_pedagogy_doc:     'Pädagogisches Zusammenfassungsdokument exportieren 📄',
    export_doc_main_title:       'Pädagogische Zusammenfassung — Waldorf-Archiv',
    export_doc_filename:         'Pädagogische Zusammenfassung - {grade} - {topic}.docx',
    export_doc_grade_line:       'Klasse: {grade} (Alter {age})',
    export_doc_topic_line:       'Thema: {topic}',
    export_doc_section_grade:    'Schritt A — Entwicklungsbild',
    export_doc_section_web:      'Schritt B — Themenrecherche',
    export_doc_section_theory:   'Schritt C — Theoretischer Hintergrund',
    export_doc_section_inspiration:'Schritt C — Inspiration',
    export_doc_section_curriculum: 'Schritt C — Blockplanung',
    export_doc_section_other:    'Weitere Erweiterungen',
    export_doc_expansions_title: 'Geöffnete praktische Aspekte',
    export_doc_web_connections:  'Altersbezug',
    export_doc_no_topic:         'kein Thema',
    export_doc_need_grade:       'Bitte zuerst eine Klasse wählen',
    export_doc_error:            'Fehler beim Export',
    export_doc_generating:       'Dokument wird erstellt...',
  },

  /* ── Spanish ─────────────────────────────────────────────────────────────── */
  es: {
    meta_title:                  'Planificador de Lecciones Waldorf',
    meta_description:            'Herramienta guiada por IA para planificar lecciones Waldorf para los grados 1–8',
    header_tagline:              'Educación Waldorf',
    header_title:                'Planificador de Lecciones',
    header_subtitle:             'Planificación de lección principal guiada por IA',
    lang_label:                  'Idioma',

    nav_wizard_aria:             'Asistente de planificación de lecciones',
    nav_repo:                    'Repositorio',
    nav_repo_aria:               'Abrir repositorio de materiales',
    nav_archive:                 'Archivo',
    nav_archive_aria:            'Abrir archivo de artículos',

    btn_new_research:            'Nueva investigación',
    step_prefix:                 'Paso',
    step_a_badge:                'A',
    step_b_badge:                'B',
    step_c_badge:                'C',
    step_a_grade:                'Grado',
    step_b_topic:                'Tema',
    step_c_materials:            'Materiales',

    step1_title:                 'Elegir grado',
    step1_desc:                  'Selecciona tu grado para descubrir el plan de estudios recomendado',
    grade_label:                 'Grado',
    grade_placeholder:           'Selecciona un grado…',
    grade_age_prefix:            'Edad',
    btn_grade_submit:            'Continuar al tema',
    grade_insights_default:      'Selecciona un grado para ver perspectivas',
    grade_insights_title:        'Perspectivas para el grado {grade}',
    grade_insights_sources:      'El sistema está produciendo la imagen de edad y ampliaciones pedagógicas para el grado seleccionado...',
    grade_insights_generating:   'Produciendo imagen de edad, ideas y ampliaciones comunitarias...',
    grade_research_cancel:       'Cancelar y elegir grado de nuevo',
    grade_insights_empty:        'No se recibió contenido de imagen de edad — inténtelo de nuevo.',
    community_need_topic:        'Define un tema en el paso B para ver materiales de la comunidad.',
    community_empty_topic:       'Aún no hay materiales de la comunidad para este tema.',
    community_materials_title:   'Materiales de la comunidad',
    btn_to_step2:                'Continuar al tema',

    step2_title:                 'Elegir tema',
    step2_desc:                  'Ingresa un tema para el estudio en profundidad',
    topic_placeholder:           '',
    api_hint_step2:              'Requiere una clave API activa',
    btn_topic_research:          'Investigar tema',
    btn_to_step3:                'Continuar a materiales',

    step3_title:                 'Materiales didácticos',
    step3_question:              '¿Qué materiales deseas agregar?',
    step3_desc:                  'Agrega materiales personales, archivos de Google Drive y recursos comunitarios',
    personal_title_ph:           'Título del material',
    personal_notes_ph:           'Notas personales…',
    btn_personal_upload:         'Subir archivo',
    btn_drive:                   'Conectar Google Drive',
    btn_drive_sync:              'Sincronizar con Drive',
    drive_privacy:               'Los archivos permanecen privados',
    btn_unlock_workspace:        'Abrir espacio de trabajo',
    ws_active:                   'Espacio de trabajo activo',
    btn_restart:                 'Empezar de nuevo',

    tab_theory:                  'Teoría',
    tab_theory_suffix:           ' + Fuentes',
    tab_inspiration:             'Inspiración',
    tab_inspiration_suffix:      '',
    tab_archive:                 'Archivo',
    tab_archive_suffix:          '',
    tab_curriculum:              'Plan de estudios',
    tab_curriculum_suffix:       '',

    pinterest_title:             'Tableros de Pinterest',
    pinterest_desc:              'Descubre inspiración visual para tus lecciones',
    share_community:             'Compartir con la comunidad',
    upload_author_ph:            'Tu nombre',
    upload_title_ph:             'Título del material',
    upload_notes_ph:             'Descripción breve…',
    btn_add_community:           'Agregar a la comunidad',

    archive_title:               'Archivo de artículos',
    archive_desc:                'Busca artículos e investigaciones sobre educación Waldorf',
    archive_search_label:        'Buscar en archivo',
    archive_search_ph:           'Ingresa término de búsqueda…',
    archive_search_btn:          'Buscar',
    archive_api_hint:            'Requiere clave API',

    curriculum_title:            'Plan de enseñanza',
    expand_all:                  'Expandir todo',
    curriculum_cards_aria:       'Tarjetas del plan de estudios',
    col_day:                     'Día',
    col_topic:                   'Tema',
    col_content:                 'Contenido',
    col_art:                     'Arte',
    refresh_cloud:               'Actualizar',

    cloud_research_on:           'Investigación en la nube activa',
    cloud_research_off:          'Investigación en la nube desactivada',
    cloud_community_on:          'Comunidad en la nube activa',

    confirm_new_research:        '¿Iniciar nueva investigación? Los cambios no guardados se perderán.',
    personal_default_title:      'Material personal',

    grade_insights_loading:      'Cargando perspectivas…',
    grade_insights_fallback_note:'Estas perspectivas se basan en el conocimiento general de la pedagogía Waldorf',
    grade_part1_title:           'Imagen de edad y énfasis pedagógicos ampliados',
    grade_part2_title:           'Ideas pedagógicas prácticas para el aula',
    grade_part3_title:           'Ampliaciones y materiales comunitarios',
    dev_focus:                   'Enfoque del desarrollo',
    global_curricula:            'Planes de estudio mundiales',
    sources_label:               'Fuentes',
    typical_blocks:              'Épocas de lección principal típicas',

    no_teacher_folders:          'No se encontraron carpetas de maestro',
    no_community_grade:          'No hay materiales comunitarios para este grado',
    community_demo:              'Material de demostración',
    load_error:                  'Error de carga',

    topic_research_scanning:     'Analizando fuentes…',
    topic_research_deep:         'Investigando en profundidad…',
    btn_topic_research_again:    'Investigar de nuevo',
    web_research_title:          'Investigación web',
    web_research_age_conn:       'Conexión con la edad de la clase',

    remove_btn:                  'Eliminar',
    drive_picker_title:          'Seleccionar archivo de Drive',
    drive_file_default:          'Archivo de Drive',
    drive_picked:                'Seleccionado: {name}',
    drive_picked_none:           'Ningún archivo seleccionado',
    drive_cancelled:             'Selección cancelada',
    drive_merging:               'Combinando materiales…',
    drive_merge_fallback_title:  'Material de Drive',
    drive_merge_fallback_note:   'Contenido de Google Drive',
    drive_merge_insp_note:       'Inspiración de Drive',
    drive_merge_curr_note:       'Plan de estudios de Drive',
    drive_connecting:            'Conectando con Drive…',
    drive_opening_picker:        'Abriendo selector de archivos…',
    drive_config_missing:        'Configuración de Drive faltante',
    drive_syncing:               'Sincronizando…',
    drive_sync_done:             'Se encontraron {count} archivos, {added} nuevos añadidos',
    drive_sync_empty:            'No se encontraron archivos',
    drive_library_title:         'Biblioteca de Drive',
    drive_library_desc:          'Archivos de tu Google Drive',
    drive_open_folder:           'Abrir carpeta',
    drive_open_file:             'Abrir archivo',
    drive_auto_loaded:           'Cargado automáticamente desde Drive',

    synthesis_banner:            'Síntesis lista',
    personal_materials_ws:       'Materiales personales',
    pinterest_board:             'Tablero de Pinterest',
    pinterest_link:              'Enlace al tablero',

    curriculum_day:              'Día {n}',
    curriculum_tap_details:      'Toca para ver detalles',
    curriculum_content_label:    'Contenido de la lección',
    curriculum_art_label:        'Actividad artística',
    curriculum_journeys:         'Viajes de aprendizaje',

    no_community_ws:             'No hay materiales comunitarios para este espacio de trabajo',
    community_teachers:          'Maestros de la comunidad',
    delete_confirm:              '¿Eliminar este material?',
    delete_aria:                 'Eliminar material',
    demo_badge:                  'Demo',

    upload_demo_saved:           'Guardado localmente (incluye archivo)',
    upload_saved:                '¡Guardado en la comunidad!',
    upload_no_file:              'Seleccione un archivo para subir',
    upload_uploading:            'Subiendo archivo...',
    upload_saved_local:          'Archivo guardado localmente en su dispositivo',
    upload_saved_cloud:          'Archivo subido a la nube y guardado localmente',
    upload_saved_local_only:     'Guardado localmente (nube no disponible)',
    upload_updated:              'Material actualizado',
    file_too_large:              'El archivo es demasiado grande (máx. 10 MB)',

    archive_alert_empty:         'Por favor ingresa un término de búsqueda',
    archive_alert_no_api:        'Se requiere una clave API para buscar',
    archive_searching:           'Buscando…',
    archive_found:               '{n} resultados encontrados',
    archive_no_results:          'No se encontraron resultados',
    archive_read_full:           'Leer completo',
    archive_no_link:             'Sin enlace',
    archive_summary_btn:         'Resumir',
    archive_summary_title:       'Resumen',
    archive_key_points:          'Puntos clave',
    archive_class_angles:        'Ángulos para la clase',
    archive_further_reading:     'Lectura adicional',
    archive_generating:          'Generando resumen…',
    archive_type_book:           'Libro',
    archive_type_lecture:        'Conferencia',
    archive_type_article:        'Artículo',
    archive_type_source:         'Fuente',
    archive_untitled:            'Sin título',
    archive_unknown_author:      'Autor desconocido',
    archives_synthesis:          'Síntesis del archivo',

    teacher_default:             'Maestro/a',

    err_supabase_config:         'Error de configuración de Supabase',
    err_network:                 'Error de red – verifica tu conexión',
    err_bad_response:            'Respuesta incorrecta del servidor',
    err_function_not_found:      'Función no encontrada',
    err_invalid_plan:            'Plan inválido',

    phase_opening:               'Apertura',
    phase_deepening:             'Profundización',
    phase_expanding:             'Expansión',
    phase_synthesis:             'Síntesis',
    phase_closing:               'Cierre',
    day_n:                       'Día {n}',

    theory_age_topic:            'Edad {age}: {topic}',
    inspiration_visual:          'Inspiración visual',
    visual_inspiration_n:        'Inspiración {n}',
    picker_script_error:         'Error al cargar el selector de Google Drive',

    btn_export_pedagogy_doc:     'Exportar documento de resumen pedagógico 📄',
    export_doc_main_title:       'Resumen pedagógico — Archivo Waldorf',
    export_doc_filename:         'Resumen pedagógico - {grade} - {topic}.docx',
    export_doc_grade_line:       'Clase: {grade} (edad {age})',
    export_doc_topic_line:       'Tema: {topic}',
    export_doc_section_grade:    'Paso A — Imagen de edad',
    export_doc_section_web:      'Paso B — Investigación del tema',
    export_doc_section_theory:   'Paso C — Antecedentes teóricos',
    export_doc_section_inspiration:'Paso C — Inspiración',
    export_doc_section_curriculum: 'Paso C — Planificación de bloque',
    export_doc_section_other:    'Expansiones adicionales',
    export_doc_expansions_title: 'Aspectos prácticos abiertos',
    export_doc_web_connections:  'Conexión con la edad',
    export_doc_no_topic:         'sin tema',
    export_doc_need_grade:       'Seleccione una clase antes de exportar',
    export_doc_error:            'Error al exportar el documento',
    export_doc_generating:       'Generando documento...',
  },
};
